### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Dablakbandit** [jadedcat/AS2Configs#110]
Using the latest client from curse client and the latest server files I am unable to connect to the server:

http://pastebin.com/3TLFvSML

Here is the log from fml:

http://1drv.ms/1L86pC5

**Comment by Kopo942** [comment]
Could you force a manual crash log by pressing F3 + C ingame, and then upload the whole log and link it here? Server's rejecting some of your mods.

**Comment by Dablakbandit** [comment]
I don't know what you mean by F3 + C as it did nothing for me. But i can provide my client logs

http://1drv.ms/1QAC9zY

**Comment by Kopo942** [comment]
The server files you are using have outdated mods included. Are you sure you've downloaded the newest server pack available (version 1.1.13)? You can download the latest version from [CurseForge](http://minecraft.curseforge.com/modpacks/225550-agrarian-skies-2/files) (Agrarian Skies 2-1.1.13.zip -> scroll down for Agrarian Skies 2-1.1.13 - Server.zip).

**Comment by Dablakbandit** [comment]
I'd swear I had the latest, I will check again.

**Comment by pjfranke** [comment]
With how often it updates, Botania works good as a canary to see what version you are on.

The log you posted (2nd link, 1st post) shows Botania v201, which was shipped in the pack version 1.1.8; 1.1.13 has updated to v212, which at this point is well out of date too.  However, we have not published a pack update since that was current, so that is the most current version in the pack files.

**Comment by cblair91** [comment]
User error.
