### ISSUE TITLE
Power Grid queest

### ISSUE THREAD

**Issue by Katzujari** [jadedcat/AS2Configs#131]
I am not sure if this is a "bug" or just an human error, but there are 2 quest in Section "Power Grid" whit the same requeriment. I just complete the first one and i have the second one complete inmediatly.
Those quest are "Power Transfer" and "Power Cables". They just need to craft 1 RednNet Energy Cable...

**Comment by samuelroy21** [comment]
I don't recall seeing that quest... are you in the latest version of Agrarian Skies?

**Comment by eviltux** [comment]
Not sure if this was intentional, but I see what Katzujari is talking about. I believe it's one of the paths right after you've completed Dynamic Power. It is like this in version 1.1.14.

![2015-10-15_00 42 13](https://cloud.githubusercontent.com/assets/15135428/10504961/b3d4bfa6-72d5-11e5-927e-b1a923348af4.png)

Once you complete Power Transfer, you unlock Power Cables.
![2015-10-15_00 42 19](https://cloud.githubusercontent.com/assets/15135428/10504962/b9de6226-72d5-11e5-9ca3-c8ce6d6c6dd1.png)

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#2
