### ISSUE TITLE
Portal-in-a-box infusion crashes game with low stability altars

### ISSUE THREAD

**Issue by UndeadLemon** [jadedcat/AS2Configs#134]
I've tested this several times, and it appears that certain instability events (mostly an eye getting removed from a pedestal, or being destroyed) are causing crashes. Altars with stability greater than 50 (checked with an arcane abacus) seem to be safe, which would match up with instability being the problem (Portal infusion has a stability of 25, and random stability is capped at 25).

Once the crash happens, the infusion matrix is for all intents and purposes "corrupted" and will crash the game again if it tries to load the matrix. If the matrix is deleted (via worldedit) then the issue is fixed. I think a previous update was supposed to fix this, but it's still an ongoing issue (as of 1.1.13, at least)

**Comment by samuelroy21** [comment]
log?

**Comment by tr0nlegacy2012** [comment]
This is one of many crash reports after the infusion: http://pastebin.com/DPLpmymA
And this is the server log from one of the crashes: https://gist.github.com/tr0nlegacy2012/26caa42ec8187dfb785d

**Comment by Chinthor** [comment]
Yeah. Having the same problem. Do an issue search for is:issue is:portal. Sorry, you won't like what you find. Either roll back before the infusion or mcEdit to delete the matrix. Short term solution is get your stabilizers to over 25. Mine was right at 25, but I was missing some essentia. Things started popping off before I could race to melt down some stuff. And this bug seems to be set up by instability events (item off, item destroyed, lightning, flux, etc.) and then the crash happens when the infusion finishes. You reload, the infusion is still in progress, it finishes, and then you crash again.

**Comment by pjfranke** [comment]
As noted, you've described the problem exactly.  High instability recipes combined with an altar setup that can't ensure stability with them, can cause corruption with the Infusion Matrix.  Throw TONS of symmetrical stabilizers at the altar (botania glimmering flowers work and are cheap, as well as the floating variants are easy to place) to ensure it doesn't have instability drop far enough.
