### ISSUE TITLE
Strange problem when loading world. 

### ISSUE THREAD

**Issue by nicogranelli** [jadedcat/AS2Configs#177]
I've a pretty strange situation. When I tried to start my world (after 10 days break) it crash when I select my save. The crash log http://pastebin.com/bj0wUyde

The curious thing is at the top: 
 
> The pack has been tampered with. Do not report any errors.
> cookingbook
> origin, thaumicexpansion

As I didn't added or removed any mod, I started to research a little. Those mods were changed in the last version, so I wondered if my save was created in 1.1.13 or 1.1.14. But I remember using the cookingbooks kitchen multiblock pretty early game, so I must have started with 1.1.14.

So far I tried to bring a backup, but always the same error. Then I deleted everything and reinstalled, tested again with backups and the same. Not sure what can I do now. 

Thanks for the help :)

**Comment by samuelroy21** [comment]
that notice at the top is a small error FYI because SOMEBODY forgot to update the configuration files *cough* Jaded *cough*. As for the rest of the error, I'll take a look later.

**Comment by Trisscar05** [comment]
This is a common one among modpacks, though I cannot remember the previous reasons as to why it happened atm.
This also may be caused by any mods you might have added, if you added Optifine or something; also if the amount of RAM you had it set to use has been reset, it does that occasionally.
It's complaining about block extension and chunk loaders though, so it would seem prudent to ask if you have any of these placed in your world;
AE2 Crafting blocks (the things you use to make the giant multiblock autocrafter)
AE2 Pylons, the ones you use to store entire areas inside a drive, or indeed any areas already stored
Tinker's smeltery (you probably do have this, but good to check)
Ender Quarry from Extra Utilities
Any kind of chunk or spot loader, usually named as such
The giant tank for animal infusions from Thaumcraft, or indeed a basic infusion altar
I don't remember for sure, but if the BC quarry is still in....
Storage drawers with an attached Drawer Controller, or if they happen to be sorting drawers
The blood altar from Blood Magic with any upgrades
The portal to Alfheim from Botania
A reactor/turbine from Big Reactors
And finally, anything that is labelled as part of block or storage extension in the "Storage" area of the quest book. I haven't messed with it much, so the names escape me. XD

**Comment by nicogranelli** [comment]
I didn't add any mod. And from your list I have:
* AE2 setup (but no pylons)
* Smeltery
* Storage Drawes
* Infusion but the regular, not the animal yet
* Blood Altar
* Botania's portal
* BR's Reactor (on turbine)

Also, I think I used a chunk loader, but I'm not sure. Let's assume I did.

One thing I don't understand is how I was able to continue playing for some time, having several backups, and so far all of them have this problem. Could be something that happen when the save file is being loaded?

**Comment by Trisscar05** [comment]
Well, if it's the mobs as I seem to remember one case being, then it's because one spawned with a bugged "Infernal Mob" status effect or buff.
However, if it's ALL your backups, that's interesting and different. That would indicate an issue with either the modpack loader, the pack itself, your computer, an update to a mod, or any combo of the four. You said you left it for a while, did it say it was updating anything when you came back to the launcher?

**Comment by nicogranelli** [comment]
I haven't tried all the backups, but the 2 or 3 more recent. I will test more today.

About the update, I'm really unsure. I think I didn't update anything, and a quick check at the changelogs seems to indicate this (I remember playing with cookingbook, and that mod was added in the last update). Maybe curse update by itself? being just the launcher, shouldn't be a factor here.

Also, I tried this: I deleted the AS2 folder, reinstalled, and then started to try with backups. That should rule out bad downloads or disk errors, right?

PS: If the problem is a bugged mob, what can I do? maybe lauch the game in peaceful?

**Comment by Trisscar05** [comment]
If it's a mob, then peaceful might help, though I don't remember if the world loads with the mobs and THEN deletes them or just ignores them when loading.
....
Mk, a quick search blames everything from corrupted player data to a corrupted Forge version for this crash log. So let's do the checklist and see if anything changes, try to check between each iteration if appropriate:
-Re-backup your current version of the save and all of the backups you can find in a different location on your hard drive, just in case
-Redownload the modpack (you seem to have already done this)
-Check the amount of RAM Minecraft is being allowed by the launcher, if it's Curse it's in the Curse settings, FTB has an Options pane. It should be around 3.5-4, unless your computer has only that much, in which case about half your total RAM.
-Check where Curse is downloading the pack from, and switch servers if you can.
-If all this does nothing, redownload Curse, then perform the previous actions sans the backup of saves.

Alternately, if you'd rather do something less frustrating first, load up MCEdit and check to see if there are any chunks that are completely black that aren't just void anyway. If you find a black one, it's likely corrupted and you should try using one of the MCEdit tools to uncorrupt it or simply delete the chunk so that it respawns on world start.

**Comment by nicogranelli** [comment]
Updates:

I tried loading the save in peaciful, not good. 
I deleted all the entities with MCEdit, not good (also, it seemed not chunk was corrupted, but I don't know MCEdit well enough to ensure that).

One of the backups from the last day I played worked fine. Now I'm trying to find the newest one without the error.

**Comment by nicogranelli** [comment]
Well, finally found a non bugged backup. Lost about 3:30 hours of play. Trying to remember what I did and what is missing, the only obvious thing is the botania's portal. Probably not the only thing missing, but the biggest I remember. 

What can I do to prevent this? Can I still craft the portal (maybe in another location)? 

About the situation of having 7 backup with the error (and the false safety an automated backup process gives), could be prevented by having the habit of closing and reopening MC after some time? I'm thinking that if I hadn't played so many hours in a row, I would have detected the problem early. 

BTW, thanks Trisscar05 :)

**Comment by Trisscar05** [comment]
Problem is we have no idea what bugged in the first place. It's why this particular report is so common and has no clear culprit, it just doesn't actually say which block or entity actually corrupted. It's basically saying "Something went wrong with loading base functions", which could be caused by a whole heap of things.
The good news is that it's probably not your minecraft version, launcher, or anything else static, since you were able to get at least some of the backups to work. I'd say make sure to place the one you know works in a separate folder, and add more backups regularly to that folder, preferably with notes attached as to what you did during that time. That way if this DOES happen again, we can have a better idea of what may have caused it.

**Comment by nicogranelli** [comment]
Thanks, I will do that. 

Too bad the stack trace don't log any parameter values. I know I could use that in c#
