### ISSUE TITLE
Carpentry Bench

### ISSUE THREAD

**Issue by CaptainKriss** [jadedcat/AS2Configs#18]
In a carpentry bench i got as a reward bag reward has really wierd recipes, for example: A 4x4 hollow with oak wood makes yellorium, spruce wood in a 4x4 hollow makes cyanite and so on with the types of wood. Also if i go to the 9th page of recipes i crash. Is the op recipes intended or is it a bug?

**Comment by samuelroy21** [comment]
I don't believe it is intentional. What version are you in?

**Comment by samuelroy21** [comment]
did you mess with item IDs? it crafts plain ol' crates for me.

**Comment by pjfranke** [comment]
No, of course not intentional.  But that mod has been a source of random/odd recipes so far.  Have you been updating your pack in-place for a few versions?

You could try downloading a fresh install of AgSkies2, then copying your Saves, JourneyMap, and TCNodeTracker folders over.  Also the options file to save your preferences/keybinds.

Then launch the new instance, and see if it's behaving better.  It should still have everything you care about.

**Comment by jadedcat** [comment]
I am really starting to dislike that mod. In the save folder, under "customnpcs" find the file called "recipes" and delete it.
