### ISSUE TITLE
Sugarcane does not grow correctly after update

### ISSUE THREAD

**Issue by Blkandwhtlion** [jadedcat/AS2Configs#184]
I have been playing this for awhile. Even grew some sugarcane in the past. I updated my version to the latest and it seems everything is working but the sugarcane planting. Just in case you have doubts on my process. I put a sand block down with water next to it and put crop sticks on it. I take out sugarcane seeds. I used to have to craft them from ex nihilo seeds but now it seems sifting them from dirt works? either way I had some sugar cane already planted and got the correct seed, only to figure out I can't put it down. I tried more water, dirt, light level, etc. nothing. I hope its not a world issue? The only thing I can think of is the update broke it. 

As a weird side note, I can put the actual sugar cane on plain sand like vanilla minecraft. I don't ever remember being able to do that in the game.

I reverted to version 1.1.13 and now they plant successfully again. I will try re updating my saved world to 1.1.14 again and update. It may have been a bad file copy?

**Comment by Blkandwhtlion** [comment]
Just an update. I went back to update from 1.1.13 to 1.1.14 and it wiped my world out and defaulted all of the normal worlds again. The only way I can seem to get the world over is copying the save folder over. I'll update on this next.

**Comment by pjfranke** [comment]
If you look at the recipe for the Agricraft sugarcane seeds, they do not actually list sand as a viable soil type, even though vanilla Sugarcane can be planted on sand.

Agricraft Sugarcane can be sifted from soil, yes.  The recipes to sift Ex Nihilo sugarcane seeds have been removed, and replaced with Agricraft seeds.  You can also craft any remaining Ex Nihilo seeds into the Agricraft variants, or cross-breed to get them.

Yes, actual sugarcane can still be planted on sand, and has been that way in AS2 since the beginning as I recall.  That vanilla mechanic has never been removed, though the growing speed is so much less, and the quantity you can grow so much less, especially considering you don't need to plant it directly adjacent to water, only close enough to keep it hydrated (normal crop rules, or use sprinklers).

**Comment by Blkandwhtlion** [comment]
Thanks for your reply. 
To your first point. So sand is not how you grow it anymore? I tried dirl, can't put crops on it, and when I till the dirt adn put crops on it, I can't put the sugar cane there either. Either adjacent or not to water.

Second point. I am using Agricraft seeds. In fact when I sieve dirt I don't even see Ex Nihilo seeds anymore (the were big and brown) so your second point makes sense.

Third point: I never knew that, so I can write that off. Thanks for the update.

Finally, I will try growing them again in dirt from a new save completely. I hope my save is not corrupted, I am so close to completing the top three or four quest lines.

**Comment by pjfranke** [comment]
You should be able to throw a harvested piece of sugarcane straight on sand (no crop sticks), if the sand is adjacent to a water block (no diagonals).  So, "not how you grow it anymore?"  Yes and no. You can do like I just said on sand.  You can not grow Agricraft sugarcane on sand; it needs dirt, farmland, hummus, podzol, or one of a few other blocks.  Then you put crop sticks on that substrate, then the Agricraft seeds should plant.

Good call, I would confirm your instance is correct by testing in a new save before writing off your world.

**Comment by Blkandwhtlion** [comment]
Just to help me sleep at night, was sugarcane growing on farmed dirt a change introduced in 1.1.14?

**Comment by pjfranke** [comment]
I'll have to check one of my older savegames/backups in an older version of the pack tonight, I'll post again when I have an answer.

**Comment by pjfranke** [comment]
1.0.42 - Agricraft sugarcane required sand substrate, and only sand
1.1.8 - same
1.1.13 - same

So yes, it does seem it was a change in the 1.1.14 update.  Sorry for the confusion, I haven't played AS2 for a while (so forgot that), and only installed a clean 1.1.14 instance to use for troubleshooting the current bugreports.  Now that I think about it, in my 1.1.13 savegame I did work sugarcane up to 10/10/10 seeds on sand (of course, as it was the only viable substrate for them), but as I said, I haven't played AS2 since 8/28.
