### ISSUE TITLE
Two errors - empty single player world and jetpack mod multiplayer failure.

### ISSUE THREAD

**Issue by IsaacsLaughing** [jadedcat/AS2Configs#229]
When I run the pack in single player, I can enter the world but none of the world is.... there. http://paste.feed-the-beast.com/view/f1a65624

When I try to join a server, this happens: http://prntscr.com/afuboh. http://paste.feed-the-beast.com/view/40c4f4f4

**Comment by Trisscar05** [comment]
Which save are you entering in single player, are you able to look around when you load in or do you get a weird jerky motion when you try, and finally (not saying you should yet if you haven't) have you tried uninstalling and redownloading the pack?

**Comment by IsaacsLaughing** [comment]
Which save.....? Just a new world. I can look around but not for long before I die in the void. I don't see how to reinstall the pack...

**Comment by pjfranke** [comment]
Did you start a new map?  Or use one of the included ones?

The map type is set to a void world, so if you start a **new **map, you'll be missing a lot of stuff.  Actually, without any starter items (e.g: dirt, tree, saplings, etc) you wouldn't be able to do _anything._

**Comment by IsaacsLaughing** [comment]
*facepalms* Yeah, I didnt even pay any attention to the maps tab in the launcher. ;>.> There is still the jetpacks issue when joining servers, though.

**Comment by pjfranke** [comment]
From your log files, it seems you are playing the 1.6.4 version of Agrarian Skies, from the FTB launcher.  Not the 1.7.10 Agrarian Skies 2 from the Curse launcher.

Also, the error you are getting is because there is a mod mismatch (or version mismatch) between your client and the server for the mod "Simply Jetpacks".  The server is running 0.3.11, and yours is not. I can't see from logs whether yours is newer, or older...I would assume they're running an updated version though.

Also, you seem to have ChickenChunks installed (chunkloaders), which the server does not.

**Comment by Developaws** [comment]
As no response in more than a month, closing.
