### ISSUE TITLE
[Question] Thaumcraft nodes in world

### ISSUE THREAD

**Issue by BakermanLP** [jadedcat/AS2Configs#23]
Hello,

just a simple question. Should there be Thaumcraft nodes in the world?

Version is 1.1.8

Thanks for you answer

Michael (aka BakermanLP)

**Comment by pjfranke** [comment]
Yes, and there are.  They spawn normally in the nether, both at lava level, as well at various heights on land.

In the overworld, due to the lack of land, they all spawn down by the void, pretty much <10.  Some of the packs seem to have "cleared" the area around spawn for a large radius, so you'll need flight (and decent level) to fly far enough to find them.  But fly around down by the void level, and you'll eventually see them.

One bit of advice...the automatic scanning lens and the Thaumcraft Node Tracker mod don't play nice together.  Wear Goggles of Revealing, or one of the variants (Sanguine Helmet, Manasteel Helmet of Revealing, etc) to find them, but use a Thaumometer to scan.  Otherwise you'll get the aspects fine, but they won't be recorded in the list for later reference.

**Comment by jadedcat** [comment]
Also, try crafting nodes. You can make nodes.
