### ISSUE TITLE
World not "interactable" and quits responding when shutting down internal server

### ISSUE THREAD

**Issue by IIIeye** [jadedcat/AS2Configs#230]
I am seeing an issue where suddenly chests and items are no longer able to be opened or used. For a while I got around it by logging out and back in, but now it freezes up when I try to log out. I've nuked my install twice and it helps but then it keeps going back to what it was doing.

Output log:
http://pastebin.com/WVaWACJW

launcher log:
http://pastebin.com/36D2uXL4

**Comment by Trisscar05** [comment]
Turn off journeymap? It sounds like you're having lag issues, this might help with that.

**Comment by IIIeye** [comment]
Hmmm, hitting disable button doesn't do anything, so pulled the mod files from the folder. problem persists. Worse part is it's not even taxing my PC so it shouldn't lag

**Comment by Trisscar05** [comment]
Huh. Disable ArmoaBackup as well please? It can leak or fill up your memory and cause issues.
The reason I said to hit Journeymap first is because the log you provided was complaining that it couldn't version check because of an undetermined array. Assuming that is from after you attempted to reinstall, I suspect we should cover the basics.
-What's your OS and version of, Java version, and basic PC specs?
-How much RAM are you allowing the game to use?
-Have you added anything to the pack? (The mods the log will complain about whenever it crashes don't count, those are just being silly.)

**Comment by IIIeye** [comment]
pulled aromabackup as well, still broken.

Win 7 Ultimate SP1 Build 7601
Java 8u73
Intel i5-3570k@4.3ghz
16gb Ram

Not sure on allocation, as never messed with it, In fact this is my first time with non-vanilla minecraft

**Comment by Trisscar05** [comment]
Hum. Okay, just to be certain, this isn't a LAN/server and you aren't in the spawn area? (This is unlikely as hell, but good to check.)
Assuming above is false, would you mind trying to open chests and such in different chunks? (Chunks are around 16x16.)
Frankly, the vast majority of complaints of this type are multiplayer based........
Goddamnit I'm dumb. What bit OS are you running, and is the Java install a matching version?

**Comment by IIIeye** [comment]
64bit, and yes matching.

I did a complete clean install again, and tried to start a fresh game, and it continue to not work. Nope, not a LAN/server, just what it does to play solo normally, though it stalls out completely when I try to quit with the message of "shutting down internal server" and then doesn't respond.

**Comment by Trisscar05** [comment]
The hell..... Mk, to check your memory allocation, go to settings in Curse, click on the Minecraft Tab, and scroll down to "Java Settings: Maximum Memory Allocation". The bar shouldn't be allowed to use more than half of your total system RAM, and usually if the game has more than 4 or so it tends to start doing odd things, so between 3-4 is a good range.
If that doesn't fix it, I may have to send up the Bat Signal, because this is weird and possibly outside my experience. So poke to you CBlair.

**Comment by IIIeye** [comment]
It's set at 4gb allowance through the Curse launcher.

**Comment by IIIeye** [comment]
I'm thinking it is a problem with Java. I did another install with multimc, and after about 15mins it quit working as well. If I had to take a guess It's like it stops talking to the internal server, because it becomes "not responding" when trying to quit, and a pop up about the java not working or something (forgot the wording) but i've done a fresh install of the java client as well and still not working.

**Comment by IIIeye** [comment]
I seemingly was right? I reverted back to 8u72 and everything works again...so far...

**Comment by Trisscar05** [comment]
Really? Cool! I've been using 8u71 for a while, but I'll have to keep this in mind.

**Comment by foxbluefire** [comment]
I know this is a bit late, but try disabling agricraft if you (or anyone else) still have this issue. It seemed to solve the problem for me.

**Comment by IIIeye** [comment]
and it came back when I got notice of 8u77 to upgrade...

**Comment by Developaws** [comment]
@IIIeye any update on this?

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#21
