### ISSUE TITLE
Unable to craft Super Builder's Wnad. AS2 1.1.8

### ISSUE THREAD

**Issue by bsaksida** [jadedcat/AS2Configs#25]
NEI shows that i have to pour 1 worth of ardite ingot into casting table. Wand can not be placed on casting table.

**Comment by pjfranke** [comment]
That is correct, due to the way the builders wand works, with right-click being "place blocks", and shift+right-click being "place blocks only next to this row", you can't place it into the casting table by hand.

You instead need to use some sort of item movement (transfer node, itemduct, even a vanilla hopper) to "move" it to the table, which will put it in there and allow you to pour the ardite ingot over it.

**Comment by bsaksida** [comment]
I didn't thought about that. Too bad, i spawned supper building wand.
