### ISSUE TITLE
AS2 Crashes upon launch.

### ISSUE THREAD

**Issue by R4IN-** [jadedcat/AS2Configs#254]
I've tried uninstalling the pack and reinstalling it again. I've also updated Java. 

The curse client opens the mc launcher fine, then I click Play and the client loads. I see the Mojang screen and sometimes I can even get to the gui where I can select Singleplayer/Multiplayer/etc. A couple seconds later, this ( http://prntscr.com/bohm17 ) pops up and then the mc client crashes and I get this error message: http://pastebin.com/Twj1U1B2

Any help is appreciated. Thanks!

**Comment by Trisscar05** [comment]
Try disabling Headcrumbs?

**Comment by R4IN-** [comment]
It started up fine the first time when I was offline. I started it up later and I got another error. 

http://pastebin.com/cxp1PQcH

**Comment by Trisscar05** [comment]
K, checklist time to make sure nothing in the environment is being screwy;
- 3-4 gigs RAM allocated to MC, and that's half your total ram or less?
- 64bit OS, also which version?
- 64bit Java?
- Update anything recently, including system updates, Java, firewall?
- Did you update any mods when you went online?
- Go grab the FTB launcher and enter in the pack code/install/play to see if Curse is being silly (this might take a bit of searching, as I don't remember what the pack code is)

**Comment by R4IN-** [comment]
- 16GB of RAM, 4GB allocated.

- Windows 10, 64bit

- Yes, 64bit Java

- Nope, nothing updated recently.

- Again, Nope.

- Couldn't find the pack code but I tried using MultiMC to install it and it seems to work better, but I still can't get it to start up. I get this info in a log crash report: http://pastebin.com/eJk4cjUt

**Comment by Trisscar05** [comment]
Hum, MultiMC doesn't seem to have installed CofHCore. What happens if that is corrected (make sure it downloaded and try updating it if necessary)?

**Comment by R4IN-** [comment]
The thing is that only one mod is in the mods folder (BigReactors). Everything is in the config folder and the files are changed, so I couldn't just put the zip folder for CofHCore into there. I don't even know if that particular mod belongs in the config folder or in some other one.

**Comment by Trisscar05** [comment]
What...... As far as I know (given that I haven't used multimc) the mods should all be in the mods folder. It sounds a lot like MultiMC isn't installing things correctly, though I can't be certain.
Mk, previous-odd-problem-solutions time, all based on your first log. This should all be on Curse at this point:

Downgrade Java a couple releases, since sometimes it has a tendency to break MC on it's newest versions for whatever reason.
Do your best to remember what you had from Agricraft so far, then disable it and run the pack. It can be a bit buggy, and that IS one of the things your first log was complaining about. Assuming you ever got it to load in the first place it'll fix any world based issues, btw if you did get a world going at some point did you use Blood magic on some agri-crops?
Keep headcrumbs disabled.
If you were running a resource pack, turn it off, and in fact you might even need to delete it from the files for a while.
ANNNNDDD that's everything it was complaining about. Do all this stuff, load it up and post whatever log you get, and we should be able to go from there.

**Comment by R4IN-** [comment]
MultiMC just allows you to have different instances of minecraft that are easily organized and accessible. It doesn't automatically download stuff for you. All I did was drag and drop the files you get from downloading AS2 directly into the corresponding folders. Idk really.

Also, I solved the problem by just soft resetting windows :p  Thanks for all of your help.
