### ISSUE TITLE
applied energistics problems

### ISSUE THREAD

**Issue by Hopeless-Guy** [jadedcat/AS2Configs#261]
dont know if i should make an issue about each one but:
problem 1: all recipes from "applied energistics 2" cant be viewed (as if there would be no recipe for an me energy cell or everything else), they can be build without a problem but you have to look up the recipes online...
problem 2: strange font size in the (crafting)terminal
![ae2 fontsize](https://cloud.githubusercontent.com/assets/20908604/17484994/9caf0668-5d8c-11e6-910f-8785d5d1a2af.PNG)
numbers are shown fully not with the 1k and so format

problem 3?: dont know if its just an error on my side but i cant synchonize the crafting terminal with NEI, there is no option for it (search box mode can switch between "standart search" and "auto search"

**Comment by Trisscar05** [comment]
Are all of these still occurring when you restart things, like the pack or your PC?
Well in terms of 2, the font size looks normal for MC at least. Why does it seem off to you exactly?
As for 1, you mean the AE2 recipes don't appear in NEI? If so, try clicking on Item Subsets in the inventory screen to make sure those aren't dark, and if they are then right click anything you want to see that you currently cannot. (This is also a good way to hide the myriad covers and things if those fill your NEI pages too much.)
3, hum. I don't remember that being an issue last I played this pack. I normally don't leave it on while using the crafting terminal because I tend to have several things going on at once, but I don't remember it simply not working.
You may need to manually update/reinstall the mod in all honesty, but I suggest doing the slightly less work-intensive things first.

**Comment by Hopeless-Guy** [comment]
soo first: yes everything also happens when i restart the game/pack/pc/everything - everytime

the font size - yes its the "normal" minecraft font size but iirc the numbers should be alot smaller in size (with that size you cant really say how much redstone/other items i have in my system) - a picture from the ftb wiki:

![](http://ftbwiki.org/images/e/e0/ME_Crafting_Terminal_Gui.png)

thats how i remember it:-), i checked the ae2 config, but couldnt find anything useful

and with the recipes in nei - the items appear in it, but neither R nor U (or mouseclicks or whatever) show any recipes/usages (at least as long as the item is from ae2, other mods like ae2stuff, the advanced inscriber for example, show the recipe perfectly fine), and yes all tem subsets are active

personaly i have the feeling NEI and AE2 dont work together too well on my pc but idk...

**Comment by Trisscar05** [comment]
Probably bad files, no worries yo. Sometimes things download incorrectly or get corrupted, just means that you posting things here is a record for anyone else with the same issue down the line. :)
