### ISSUE TITLE
Endearing Plate doesn't work

### ISSUE THREAD

**Issue by conition** [jadedcat/AS2Configs#267]
I can't make an endearing Plate although NEI says I could make one using the smeltery with enderium and a Plate cast.

**Comment by Trisscar05** [comment]
Does the metal go into the cast and then never form, or does the smeltery refuse to even pour it?

**Comment by conition** [comment]
The smeltery refuses to pour it
And when you hover over the plate cast with shift it doesn't say that you can  use it with enderium

**Comment by Trisscar05** [comment]
Sounds like that's been disabled then. I suspect because otherwise enderium is the only material people ever use. Here's a couple sites to use for finding another material, or you could go into the configs of likely Iquana Tweaks:
http://tinkers-construct.wikia.com/wiki/Tool_Parts
http://tinkers-construct.wikia.com/wiki/Material_Stats

**Comment by pjfranke** [comment]
> And when you hover over the plate cast with shift it doesn't say that you can use it with enderium

That's your answer right there.  Many of the materials were restricted for various TiC parts, due to them being too OP.

**Comment by conition** [comment]
Ok Thank you all very much the problem is I play on a public server so I can't just change the config but I will ask somebody to do it.
