### ISSUE TITLE
SMP players are invisible to others until they die the first time.

### ISSUE THREAD

**Issue by ZizzyZizzy** [jadedcat/AS2Configs#35]
Version 1.1.8 client and server using the default SMP map with side quests.

As stated, players are invisible to each other until a player dies, then others can see that player from then on.

**Comment by samuelroy21** [comment]
did you use any outside mods? what is your java version? what os is the server?

**Comment by ZizzyZizzy** [comment]
Just the mods that came with the server download.

# java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

CentOS 6.7

**Comment by pjfranke** [comment]
Is this a new server instance, and it happened once?  Not to say that that makes it OK, or not worth looking into, only that it'll be hard to pinpoint if it can't be duplicated.  Also if the server does not have a lot of players, and now that they've all died the problem is no longer a problem.

Or does this happen every reboot, relog, etc?

You could post the Forge logs that have the players deaths noted, so any discrepancies can be found.

**Comment by ZizzyZizzy** [comment]
Brand new server instance created with the server download.

It is repeatable by deleting everything and re-deploying. All new players are invisible to others until they die. Restarting the server doesn't do anything. The new player must die to become visible again.

**Comment by cblair91** [comment]
Make sure that the server.properties render distance is set to at least 4. Anything under that will cause entities to glitch and become "invisible"

**Comment by ZizzyZizzy** [comment]
It is set to 10, and it only happens until that player has died. Render distance is not an issue here.

**Comment by cblair91** [comment]
Could you update your pack to the latest (1.1.13) and see if the issue is still occurring.

http://minecraft.curseforge.com/modpacks/225550-agrarian-skies-2/files

**Comment by MarshMilo100** [comment]
no responses after 3 days...
