### ISSUE TITLE
Baubles inventory crashes

### ISSUE THREAD

**Issue by coranium** [jadedcat/AS2Configs#50]
My ring of magnetism from Botania that was equipped on the baubles inventory somehow turned into an assassin's leggings(from mod customnpcs) after the latest update. game crashes when i try to un-equip the assassin leggings.

Crash report here:http://pastebin.com/F0smaMuC

**Comment by pjfranke** [comment]
What version did you update from?  This issue came up on the forums a while back during an update.  You can restore your backed up instance from before the update, restore your game-save from before the update, then remove your items from the baubles slot before updating again.

Or, it appears the Baubles inventory is stored at:
Curse\Instances\[Instance name]\saves\[world name]\playerdata\[userID].baub
Curse\Instances\[Instance name]\saves\[world name]\playerdata\[userID].baubback

You could try just deleting those two files, then re-launching your save and giving yourself the items back that were lost.
