### ISSUE TITLE
All textures are white?

### ISSUE THREAD

**Issue by silversatyr** [jadedcat/AS2Configs#52]
On start-up, when the main menu appears, it's all white in the background where usually landscape would appear.

When the game map loads it says something about AWWayBook being missing, then when it loads everything is white - there's no textures for anything bar a few items like Bibliocraft stuff - everything else is a white square.

I tried uninstalling and reinstalling. I tried adding another version of Blood Magic. I tried adding resource packs. Nothing changes it.

Any help would be appreciated as I enjoyed the last Agrarian Skies and would like to enjoy this one as well.

**Comment by silversatyr** [comment]
Ah, I found the answer. Memory. >.<;

**Comment by nevercast** [comment]
Can you clarify what you meant by memory? Which memory in-particular? RAM? What did you need to do to fix it? Is this solved?

**Comment by pjfranke** [comment]
@nevercast If you are having an issue with your game, please open a new issue for help with it.  Given that the person who opened this closed it themselves, I suspect it is solved.

**Comment by nevercast** [comment]
@pjfranke Correct that I it seems to be solved. The solution was not clearly specified though. Had hoped @silversatyr would share some light on it.

I'll leave this issue be as it's closed. Thanks.

**Comment by pjfranke** [comment]
Well, often when that issue has been mentioned in the past, it's due to not enough RAM allocated to the game, such as giving it <1GB via the launcher.

i can run AS2 on 1750MB, so as long as a person's system has 4GB, and they close all other programs (particularly browsers), it should be playable.  If they have enough system ram, and can give Minecraft 3GB, that's been plenty for all the packs I've ever played, although I never use resource packs, and especially don't use 32x ones.
