### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Berindei** [jadedcat/AS2Configs#53]
So... I was playing some AS2, everything was fine, I closed the game and I went to sleep. Next day I wake up, turn on my PC, and I try to load the map, but it crashes before I enter the world. I tried to use a backup, but it won't work. In the crash report, it says I tempered with the pack, but I didn't. It also says something about thaumic expansion and redstone arsenal.

Crash report: http://pastebin.com/3AX294Vb

**Comment by pjfranke** [comment]
The message from Packguard is not applicable to your pack, due to an incorrect config file.  The mods it lists are a part of the pack.

Unfortunately the crashlog does not nail down a particular thing that is crashing your world, that anyone else is also having an issue with.  The best course of action is to roll back to your last known good Aroma Backup from before you shutdown.

**Comment by Berindei** [comment]
The interesting part is: I tried to use a backup, but it still crashes. I could try using older backups, but I am afraid it's not gonna work and I would lose to much progress.

**Comment by thesixler** [comment]
I'm having almost this exact same problem. Last night, everything's fine, I was hooking up storage buses to my AE network, nothing crazy, but this morning, crash city. I've tried 3 backups now.

I guess technically I updated blood magic but it was recommended after another crash issue i was facing upon summoning elementals.

But my pack guard is saying that I changed this 
PackGuard|ADDITION: The following mods have been added: origin, thaumicexpansion
	PackGuard|REMOVAL: The following mods have been removed: BiomeTweakerCore
	

log: http://pastebin.com/91fZREvP

**Comment by pjfranke** [comment]
```
Description: Exception in server tick loop
 
java.lang.ArrayIndexOutOfBoundsException: 7
        at cofh.redstonearsenal.block.ItemBlockStorage.func_77667_c(ItemBlockStorage.java:28)
```
The blocks that Java code is referring to is blocks of Fluxed Electrum and Fluxed Crystals.  If you aren't using one of those in your world for anything, the crash really doesn't make sense.  Unfortunately the only solution that comes to mind is to roll back far enough to find a working backup.

@thesixler , your pastebin has been deleted (likely because you got it working), so I never was able to attempt to figure out your issue.

https://github.com/CoFH/RedstoneArsenal/blob/master/src/main/java/cofh/redstonearsenal/block/BlockStorage.java
