### ISSUE TITLE
Pure Certus Quartz are obtained from Fluix Seeds?

### ISSUE THREAD

**Issue by MacAndSwiss** [jadedcat/AS2Configs#7]
Please don't yell at me, this is my first time dealing with a bug that is this game breaking. When I make fluix seeds and I throw them into the water, everything is fine, but for some reason, they turn into pure certus quartz instead of the pure fluix crystal. 

http://imgur.com/cfzP6g7 - This is a picture of my current setup.

Replication: 
 1. Craft a fluix seed.
 2. Throw into water, wait.
 3. When it is fully grown it randomly changes into a pure certus quartz. 

I'm not sure if I am the only one having this issue, or if this is just my client, I have tried relogging, etc. I am on version 1.1.6 of the modpack.

**Comment by Infernalized** [comment]
have you tried updating to the recent version of AS2 (1.1.8)?

**Comment by MacAndSwiss** [comment]
I am on a server, and I am not the owner.

**Comment by Infernalized** [comment]
Do you know if any of the configs were changed from the default version?

**Comment by shadowfacts** [comment]
> I am on a server, and I am not the owner.

Can you reproduce this in single player 1.1.8?

**Comment by Infernalized** [comment]
I just tested this in 1.1.6 your version and I was not able to duplicate it. The only other things I can think of is either there is a config change somewhere or there is something else wrong. You can try using the crystal growth chamber to grow your crystals instead of using water. (its also faster than the water)
