### ISSUE TITLE
Found an issue with Pack Guard

### ISSUE THREAD

**Issue by BeaudoinC** [jadedcat/AS2Configs#73]
For whatever reason, the 'tamper warning system' mod known as "Pack Guard" was causing an issue, and needed to be deactivated for me to launch correctly. I suggest removing this or listing it as an issue to that mod creator.

I have not tampered with the pack other than removing Pack Guard.

Can't figure out how to hide the crash report in the spoiler but the bug is surrounding Pack Guard. System details from the report below.

	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.8.5
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 374148760 bytes (356 MB) / 1067974656 bytes (1018 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -Xms512m -Xmx2048m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1469 134 mods loaded, 133 mods active

**Comment by pjfranke** [comment]
You are not running the pack via the CurseVoice launcher. That is fine, alternative launchers do not cause a problem, and are required for Linux and OSX. 

The reason I can tell that, and why you are having an issue, is because you are running the pack with Java7. The PackGuard shipped with 1.1.8 is only compatible with Java8, which the CurseVoice launcher includes and runs Minecraft with. 

Of course, I do see you're on OSX too, which is why you're not using CV. You can upgrade PackGuard, disable it, or update your Java to fix the issue. 

This issue was raised to the author of PackGuard, and a compatible update has been released. The next version of AS2 resolves this issue.
