### ISSUE TITLE
update deleted my save world?

### ISSUE THREAD

**Issue by DiploBlock** [jadedcat/AS2Configs#82]
I logged on to curse and saw and update for AS2 was available. Downloaded the update. Opened agrarian skies 2 and clicked on my "sweet reminice" save that i have like 80 hours into. I get dropped into the default "sweet reminice" world and all my progress is gone except my death markers. I found the save file under curse and it is from the time I stopped playing yesterday. I really don't want to start fresh. Any input is appreciated.

**Comment by MarshMilo100** [comment]
This is just the way that curse works, it replaces folders with the same names that are in the update/download. Next time you should change the name of your world to something other than the default. you can get a complete backup of your instance from before you updated from the 'Curse\Minecraft\Backups\[instance name]\saves' folder

**Comment by pjfranke** [comment]
If you have not renamed your savegame since you started playing the provided map, yes, it would get replaced when the update is applied.  Yours is likely still named "SweetReminice - Easy", correct?

You could either restore the backup from your AromaBackup folder, or you can find your save as it was in the "Curse\Minecraft\Backups\[instance name]\saves" folder.

When restoring it into the updated Instance\saves folder, make sure to rename your save's folder to a different name, to prevent this being an issue in the future.

**Comment by DiploBlock** [comment]
i found it in the "Curse\Minecraft\Backups[instance name]\saves" folder now what do i do with it?

**Comment by MarshMilo100** [comment]
RENAME YOUR SAVE FILE, then place it in your saves folder withing your active agskies2 instance in the curse folder.

**Comment by DiploBlock** [comment]
thanks trying that now. sorry for being noobish.

**Comment by DiploBlock** [comment]
It worked. thank you. I actually had to post it in "curse/minecraft/instances/agrarianskies2/saves" for it to recognize the file.

**Comment by pjfranke** [comment]
That is the correct location. We may not have been clear on saying exactly where it goes.
