### ISSUE TITLE
unable to make a super building wand 

### ISSUE THREAD

**Issue by ahmed4455666** [jadedcat/AS2Configs#89]
so when i try to make a super building wand by pouring molten ardite on normal building wand on casting table i keep right clicking on the casting table with the building wand nothing happen

**Comment by pjfranke** [comment]
That is correct, due to the way the builders wand works, with right-click being "place blocks", and shift+right-click being "place blocks only next to this row", you can't place it into the casting table by hand.

You instead need to use some sort of item movement (transfer node, itemduct, even a vanilla hopper) to "move" it to the table, which will put it in there and allow you to pour the ardite ingot over it.

Previously mentioned in https://github.com/jadedcat/AS2Configs/issues/25
